Increased in-cloud convective scavenging coefficients
NorESMhub/OSLO_AERO pull request #30
Opened 2024-07-04 12:09 UTC by oyvindseland

Increased in-cloud scavenging coefficent for accumulation and coarse mode sea-salt, and aqueous phase produced sulfate.
Same changes as in the Forces version but modified so it use the same structure and syntax as the restructured Oslo-Aero.

2024-07-04 17:34 UTC, gold2718 requested changes
I'm not sure about the logic and can submit my suggestions as a PR to your branch if you want.

2024-07-04 17:34 UTC, gold2718 commented on src/oslo_aero_depos.F90
> +! OS 240207 Increase scavenging efficiency for large soluble particles.
`git blame` does a good job of showing who made a change and when, we don't really need these inserts.
```suggestion
! Increase scavenging efficiency for large soluble particles.
```

2024-07-04 17:34 UTC, gold2718 commented on src/oslo_aero_depos.F90
> +              if (lphase==1.and.mm.eq.l_ss_a2.or.mm.eq.l_ss_a3.or.mm.eq.l_so4_a2) then
This seems like odd logic. Is it okay to make these changes even if `lphase` is _not_ `1`? That what is what you have. If `lphase` must be `1`, see this alternative.
```suggestion
              if ((lphase==1).and.((mm==l_ss_a2).or.(mm==l_ss_a3).or.(mm==l_so4_a2))) then
```

2024-08-06 10:33 UTC, gold2718 commented
@oyvindseland, have you had a chance to look at my suggestions and questions?

2024-08-06 10:50 UTC, oyvindseland commented
Hi. Yes I agree with your suggestions. Updated the commit.

2024-08-20 07:29 UTC, gold2718 approved these changes
Looks good now!

2024-08-20 07:30 UTC, merged